# Generated by Django 3.2 on 2021-05-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_brand_product_productitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descrição do produto",
                max_length=5000,
                null=True,
                verbose_name="Descrição",
            ),
        ),
    ]
